### ISSUE TITLE
88-1: Consider input for video on VDM

### ISSUE THREAD

**Issue by peterwvj** [overturetool/overturetool.github.io#18]
The idea is to resume work on producing a video on VDM targeting the industry (related to issue #14). The task associated to this action is to consider what the message and content for such a video could be. Afterwards @pglvdm  will take an action to create such a video.

**Comment by nickbattle** [comment]
I talked with Peter about this briefly after the last Core NM (Dec 6th).

There are many problems explaining the benefit of VDM - or formal specification generally - to industry. If there was an obvious way to understand what FM was offering (an obvious _value proposition_), then such methods would already be widely adopted. So we can expect an uphill struggle.

I think what it comes down to is making a very clear case for what we propose - preferably one that solves existing/known problems in industry and/or makes businesses more efficient. Since formality is the opposite of "chaos", a fertile area to consider would be any chaotic consequences of informal development. That will take us directly into the path of (what you might call) controlled-chaotic methods - agile techniques designed to produce results quickly. These are very much "industry norm" at the moment, which means even more care must be taken to explain what is wrong here or how we can improve it. Rapid delivery does have a commercial advantage, but poorly controlled rapid development will result in undocumented unmaintainable systems (technical debt). This is well known, but I've never seen any clear analysis of the actual costs - plus this only matters for systems that have to be maintained for some time. Some systems are almost "single use" and become obsolete quickly, in which case perhaps a rapid chaotic development isn't unreasonable.

I would avoid mentioning the "safety critical" areas. Obviously the benefits of - necessity for - formality here is well known, but a general audience will just this "yes, but we don't do that." and switch off.

For heaven's sake avoid any mention of formal proof or mathematics. Tool support is worth mentioning though.

I would also avoid any discussion of the actual languages or notations. This matters to engineers using the methods, but the first people to convince are not the ones writing the models. There is perhaps a second stage of "presentation" once a business has accepted that the idea is worth considering, aimed at the people who will use the methods. This is all about abstraction and notation, tools and so on, but the commercial and business folk don't need to worry about that to start with, and you will lose them if you try.

So I think what it comes down to is us describing **what we believe in**. What is the "Formal Manifesto" of simple points that we propose, and what advantage does that offer a business? Critically, what evidence do we have to back that up? Note, the result is likely to be independent of the actual formalism used, which means we may be able to involve other groups who believe the same things.

We ought to know what we believe in already, but I've not seen a simple crisp definition beyond "modelling helps". We must do better than that to be taken seriously.

Discuss :-)

**Comment by nlmave** [comment]
Hi Nick,

It's a pretty grim picture you're sketching:

Observation (1)
> If there was an obvious way to understand what FM was offering
> (an obvious _value proposition_), then such methods would already
> be widely adopted.

Define _widely adopted_; the situation in programming languages is not 
much different, just look at 
http://www.tiobe.com/index.php/content/paperinfo/tpci/index.html; so I 
think this is a complete non-issue. There ain't no silver bullet, so 
let's not pretend we offer one either.

Observation (2)
> I would avoid mentioning the "safety critical" areas.

It's one of the few application areas where the FM community actually 
has made a difference, including recommended practice of formal 
techniques in standards, such as the higher common criteria for security 
or DO-178C/DO-333. Don't slaughter the chicken that lays the golden 
eggs!

Observation (3)
> For heaven's sake avoid any mention of formal proof or mathematics.

Yes, let's pretend it is easy and the problem simply will go away. Not 
so! These myths were debunked already long ago. There is no free lunch; 
let's be honest about it. What we should focus on is making our results 
more accessible and usable.

Observation (4)
> I would also avoid any discussion of the actual languages or
> notations.

Then there is nothing left to say... it's like claiming we cannot use 
English any more!

> So we can expect an uphill struggle.

If it was so easy, it wouldn't be fun!

> I think what it comes down to is making a very clear case for what we
> propose - preferably one that solves existing/known problems in
> industry and/or makes businesses more efficient. Since formality is
> the opposite of "chaos", a fertile area to consider would be any
> chaotic consequences of informal development. That will take us
> directly into the path of (what you might call) controlled-chaotic
> methods - agile techniques designed to produce results quickly. These
> are very much "industry norm" at the moment, which means even more
> care must be taken to explain what is wrong here or how we can improve
> it. Rapid delivery does have a commercial advantage, but poorly
> controlled rapid development will result in undocumented
> unmaintainable systems (technical debt). This is well known, but I've
> never seen any clear analysis of the actual costs - plus this only
> matters for systems that have to be maintained for some time. Some
> systems are almost "single use" and become obsolete quickly, in which
> case perhaps a rapid chaotic development isn't unreasonable.

Chaotic development is an artifact of an immature market place facing 
sheer unlimited growth; the words "engineering" and "discipline" are 
almost meaningless. Software complexity continues to grow exponentially 
but the techniques used to master this simply cannot keep up (by the 
way: we are no exception). Innovations are jumped upon to fill yet 
another gap, sometimes providing cool results, but typically still 
remain fundamentally flawed, mainly because of the technical debt in the 
legacy upon which it is build. And the legacy is big and here to stay...

> This matters to engineers using the methods, but the first
> people to convince are not the ones writing the models. There is
> perhaps a second stage of "presentation" once a business has accepted
> that the idea is worth considering, aimed at the people who will use
> the methods. This is all about abstraction and notation, tools and so
> on, but the commercial and business folk don't need to worry about
> that to start with, and you will lose them if you try.

I think that is an under estimation of the potential customer; you first 
have to figure out what kind of customer we are talking about, see 
https://en.wikipedia.org/wiki/Technology_adoption_life_cycle ; how can 
we convince the early adopters? Forget about the others - it's like 
beating a dead horse [it won't go anywhere].

> So I think what it comes down to is us describing WHAT WE BELIEVE IN.

Yes! Hurrah! Inside-out reasoning; I fully agree. I found this talk 
inspiring: 
http://www.ted.com/talks/simon_sinek_how_great_leaders_inspire_action

So what DO we believe in?

> What is the "Formal Manifesto" of simple points that we propose, and
> what advantage does that offer a business? Critically, what evidence
> do we have to back that up? Note, the result is likely to be
> independent of the actual formalism used, which means we may be able
> to involve other groups who believe the same things.

Belief (religion) and Evidence (science) are non-compatible usually :-)

So here is why I use formal techniques:
- I want to understand the problem
- I want to convey this understanding with others
- I want to convince myself that they see the problem exactly in the 
same way as I do
- I want to propose a solution to the problem
- I want to communicate this solution succinctly with others
- I want to demonstrate that this solution is inherently sound and 
complete
- I want to demonstrate that this solution is indeed an answer to the 
problem
- I want to be able to repeat this process with predicable outcome

What engineer wouldn't want this?

> We ought to know what we believe in already, but I've not seen a
> simple crisp definition beyond "modelling helps". We must do better
> than that to be taken seriously.

I'm afraid that no one will take us seriously if we do not use our own 
invented medicine.

> Discuss :-)

Well, here is my two cents worth ;-)

**Comment by nickbattle** [comment]
​Remember, we're looking for idea about how to structure a video or
presentation of some sort, which is directed at "industry". Admittedly that
audience is rather poorly specified, but my comments (and responses) are
aimed at trying to make that presentation successful. That's slightly
different to us just presenting "truths". - of course we mustn't fib, but
there are good ways and bad ways to convince someone that something is
beneficial.

I'm assuming the audience isn't comprised of engineers. Engineers (at
least, ones that get their hands dirty) don't make decisions about strategy
and methods. I think we have to convince CTOs and business leaders to
*allow* their engineers to look at this first - though it might be possible
to persuade some engineers to apply upward pressure, if the upper layers
just want to pad out their CVs with the latest cool ideas (and they do),
that won't work.

so I think
> ​[lack of adoption] is a complete non-issue. There ain't no silver bullet,
> so let's not pretend we offer one either.
>

​Sure. But I was talking about the lack of a clear value proposition, which
is central. If we had one, I claim adoption would be wider than it is.
Perhaps adoption per-se is a poor measure, but the absence of a value
proposition kills our argument.​


> Don't slaughter the chicken that lays the golden eggs!
> ​ [regarding critical systems].​
>

​If we do this, we will only be able to sell the idea to critical systems
businesses. As I said, normal business will just think, "Yes, but that's
not what we do."​


> Yes, let's pretend it is easy and the problem simply will go away. Not so!
> These myths were debunked already long ago. There is no free lunch; let's
> be honest about it. What we should focus on is making our results more
> accessible and usable.
>

​This is about careful marketing. Even the Amazon TLA+ paper agrees with
me. You must limit the exposure of people - early at least - to the
complicated details, else they will ignore you.​ The audience isn't made of
engineers.


> > I would also avoid any discussion of the actual languages or notations.
> Then there is nothing left to say... it's like claiming we cannot use
> English any more!
>

​Think about the audience. They aren't engineers, they're business people.
Perhaps that's where we differ.?


> Chaotic development is an artifact of an immature market place facing
> sheer unlimited growth; the words "engineering" and "discipline" are almost
> meaningless. Software complexity continues to grow exponentially but the
> techniques used to master this simply cannot keep up (by the way: we are no
> exception). Innovations are jumped upon to fill yet another gap, sometimes
> providing cool results, but typically still remain fundamentally flawed,
> mainly because of the technical debt in the
> legacy upon which it is build. And the legacy is big and here to stay...
>

​OK, that's a nice description of the problem. Now we need to add the
consequences, and why that costs money. And then we add the *value
proposition* which recovers that money, or even saves some.​


> I think that is an under estimation of the potential customer; you first
> have to figure out what kind of customer we are talking about, see
> https://en.wikipedia.org/wiki/Technology_adoption_life_cycle ; how can we
> convince the early adopters? Forget about the others - it's like beating a
> dead horse [it won't go anywhere].
>

​Mmmm, maybe. It's probably right that we think about the adoption curve,
but FM isn't a new technique. It may be the case that growth in adoption
would follow the same pattern as (say) a new technology use or method, but
I'm not absolutely sure. For one thing, the entire length of the curve is
contaminated with the same prejudice - FM is hard, out dated and
non-scalable. I claim that would distort the normal adoption process, so we
do have to be careful here.

But yes, early adopters will help us, if we can find them.​


> Belief (religion) and Evidence (science) are non-compatible usually :-)
>

​Yes :-)  I mean belief in the evidence-backed sense of what our value
proposition is.​


> So here is why I use formal techniques:
> ​<good thing>
> What engineer wouldn't want this?
>

​Sure. But where is your value proposition? Why does this make business
sense? Don't explode and say it's obvious: it's not. If it were obvious
(and true) it would have been adopted.


> Well, here is my two cents worth ;-)


1p back ​:-)​

**Comment by nlmave** [comment]
Hi Nick,

Many thanks for the response; it pretty much consolidates earlier 
discussions on this subject.

Nick Battle wrote on 2016-02-02 10:03:
> ​Remember, we're looking for idea about how to structure a video or
> presentation of some sort, which is directed at "industry".
> Admittedly that audience is rather poorly specified, but my comments
> (and responses) are aimed at trying to make that presentation 
> successful.

So were mine - I don't think we disagree about intent; but most of your 
comments where about what we shouldn't do or shouldn't say. My main 
problem is that I simply do not agree to some of your observations.

> That's slightly different to us just presenting "truths". - of course
> we mustn't fib, but there are good ways and bad ways to convince 
> someone
> that something is beneficial.

So, what are these good ways then, from your point of view? You previous 
messages did not offer many alternatives.

> I'm assuming the audience isn't comprised of engineers. Engineers (at
> least, ones that get their hands dirty) don't make decisions about
> strategy and methods. I think we have to convince CTOs and business
> leaders to *allow* their engineers to look at this first - though
> it might be possible to persuade some engineers to apply upward
> pressure, if the upper layers just want to pad out their CVs with
> the latest cool ideas (and they do), that won't work.

This is not my experience; either CTOs have an engineering background 
themselves or they will involve engineers in the decision making; as any 
marketing book will tell you - it is a matter of multi-level selling. 
The basic question "what's in it for me" needs to be answered for each 
group that we consider stakeholder in the technology adoption process. 
Can we agree on a list of stakeholders?

>> ​[lack of adoption] is a complete non-issue. There ain't no silver
>> bullet, so let's not pretend we offer one either.
> 
> ​Sure. But I was talking about the lack of a clear value
> proposition, which is central. If we had one, I claim adoption would
> be wider than it is. Perhaps adoption per-se is a poor measure, but the
> absence of a value proposition kills our argument.​

I agree that the value proposition is poorly defined and must be 
improved, but claiming that it is absent is simply not true.

>> Don't slaughter the chicken that lays the golden eggs!
>> ​ [regarding critical systems].​
> 
> ​If we do this, we will only be able to sell the idea to critical
> systems businesses. As I said, normal business will just think,
> "Yes, but that's not what we do."​

That's of course not true either; you can achieve growth in many ways, 
but easiest is to grow in the known product / known market combination. 
That was what I hinted at; if you want to do cross-selling (known 
product in new market), you obviously have to express your benefits in 
terms of their concerns; using your track-record in your known market to 
show credibility. And this is of course much harder! I'm not against it, 
I just want to warn you that our success rate is therefore likely 
smaller, and given the limited resources we have I am not sure we should 
go that way. I believe or "home market" has more than sufficient 
opportunities for growth.

>> Yes, let's pretend it is easy and the problem simply will go away.
>> Not so! These myths were debunked already long ago. There is no free 
>> lunch;
>> let's be honest about it. What we should focus on is making our 
>> results
>> more accessible and usable.
>> 
> 
> ​This is about careful marketing. Even the Amazon TLA+ paper agrees
> with me. You must limit the exposure of people - early at least - to 
> the
> complicated details, else they will ignore you.​ The audience isn't
> made of engineers.

Yes, very much so in the case of TLA (for those who ever witnessed a 
specification in that notation). My point is more general: our unique 
selling point *IS* our notation; it is at the heart of everything we do. 
We have to find a clever way to make that point without showing (specs 
considered scary) details. The obvious way to do that is to illustrate 
its impact during design and analysis (the competence of asking 
questions [and proposing solutions] that matter to the stakeholder).

>>> I would also avoid any discussion of the actual languages or
>>> notations.
>> Then there is nothing left to say... it's like claiming we cannot
>> use English any more!
> ​Think about the audience. They aren't engineers, they're business
> people. Perhaps that's where we differ.?

I won't reiterate my point of the plurality of the target audience and 
the need for multi-level selling. But I have another point and that is 
that our notation is easier to adopt than most other formal techniques 
available.

>> Chaotic development is an artifact of an immature market place
>> facing sheer unlimited growth; the words "engineering" and 
>> "discipline"
>> are almost meaningless. Software complexity continues to grow 
>> exponentially
>> but the techniques used to master this simply cannot keep up (by the 
>> way: we
>> are no exception). Innovations are jumped upon to fill yet another 
>> gap,
>> sometimes providing cool results, but typically still remain 
>> fundamentally
>> flawed, mainly because of the technical debt in the legacy upon which 
>> it
>> is build. And the legacy is big and here to stay...
> 
> ​OK, that's a nice description of the problem. Now we need to add
> the consequences, and why that costs money. And then we add the *value
> proposition* which recovers that money, or even saves some.​

Why do you assume that saving money is at all important? Is that the 
(short-term) objective that Joe-the-average-manager really worries 
about? I would argue that [cutting down] development time is prime; 
that's what keeps him awake at night.

>> I think that is an under estimation of the potential customer; you
>> first have to figure out what kind of customer we are talking about, 
>> see
>> https://en.wikipedia.org/wiki/Technology_adoption_life_cycle ; how
>> can we convince the early adopters? Forget about the others - it's 
>> like
>> beating a dead horse [it won't go anywhere].
> 
> ​Mmmm, maybe. It's probably right that we think about the adoption
> curve, but FM isn't a new technique.

C has been around for a while now too and it is still being adopted 
quite often...

> It may be the case that growth in adoption would follow the same 
> pattern
> as (say) a new technology use or method, but I'm not absolutely sure.
> For one thing, the entire length of the curve is
> contaminated with the same prejudice - FM is hard, out dated and
> non-scalable. I claim that would distort the normal adoption process,
> so we do have to be careful here.

Well, then you have to back up your claim. With respect to prejudice, 
again, most of them are myths or partial truths - that usually similarly 
apply to the "solutions" offered or practices preached by those that 
make these same claims. The only way to deal with this is to take those 
prejudices head-on, first of all by being fair on what we can and cannot 
do. If they will not accept this at face value, stop wasting time 
convincing non-believers and move on.

> But yes, early adopters will help us, if we can find them.​

We are educating quite a few of them in universities in DK, UK and 
Japan, how can we enable those young enthusiastic professionals to make 
their case in their companies, convince their managers?

>> Belief (religion) and Evidence (science) are non-compatible usually
> :-)
>> 
> 
> ​Yes :-) I mean belief in the evidence-backed sense of what our
> value proposition is.​

I wish evidence would make a difference; in practice it is hardly ever 
perceived as that. One of the key problems in our field is these kind of 
(management) decisions are not taken rationally as there is no history 
of empirical research. I had an interesting discussion the other day 
with a company that provides a very advanced facility for metric based 
code analysis and they pretty much confirm this attitude. Having said 
that, of course we need to provide credible evidence as best as we can, 
but don't expect miracles from it. It is just one part of the 
problem-promise-proof-push marketing paradigm.

The best convincing evidence we can provide IMHO is that we do ourselves 
as we preach. I'd like to hear your opinion about that!

>> So here is why I use formal techniques:
>> ​<good thing>
>> What engineer wouldn't want this?
>> 
> 
> ​Sure. But where is your value proposition? Why does this make
> business sense? Don't explode and say it's obvious: it's not. If it 
> were
> obvious (and true) it would have been adopted.

Well, it _is_ obvious: to prevent waste. Which is, by the way, also the 
key motivator for the agile manifesto.

Two more cents,
Marcel

[ps. I'd like to see a few more tokens from other Overture members too 
on this subject - it may seem as an argument for argument sake 
(certainly not my goal), but it is clear that there is no consensus 
among us on what our message really is and how we get this message 
across convincingly to a [diverse] audience]

**Comment by pglvdm** [comment]
I can follow the argument from both of you. Seen from my side if we produce a new video we need to enable the multi-level selling Marcel talks about AND we need to use all the good arguments we have. In my opinion that is a matter of both talking about some of the successes in industrial settings (including the safety-critical ones) as well as talking about the tool support and the community supporting that. My recommendation is that we think constructively about what storyline to use in such a video and then use that to compose some slides that can back it up. That is what I did for the requirements video and IMHO that is at least progress. This IFF we are to make another video I would suggest that we discuss a constructive storyline and see if we can agree upon that (and I would agree with Nick not to focus on the proof aspects).

**Comment by nickbattle** [comment]
Hi Marcel,

(some bits deleted for brevity)

On 4 February 2016 at 10:42, Marcel Verhoef <notifications@github.com>
wrote:

> So, what are these good ways
> ​[to convince people something is beneficial], from your point of view?
> You previous
> messages did not offer many alternatives.
>

In general​, identify a problem that you can both agree that they have, and
which causes pain. Then show them a solution that doesn't cause too much
pain to implement, either directly or via its consequences.

​The specifics​ are our value proposition, more of which below.

This is not my experience; either CTOs have an engineering background
> themselves or they will involve engineers in the decision making; as any
> marketing book will tell you - it is a matter of multi-level selling. The
> basic question "what's in it for me" needs to be answered for each group
> that we consider stakeholder in the technology adoption process. Can we
> agree on a list of stakeholders?
>

​OK, so we have to be clear about who we are approaching.​ My experience
here is based mostly on ICL/Fujitsu, which has a managerial culture
(management decides things rather than enabling engineers to do things, as
in an engineering culture). Small projects within the company may be
persuadable at an engineering level, must most of our projects are large
Government or national-scale utilities, where the projects have layer upon
layer of management. Only the bottom levels are really very technical.

​So if we have a mixed audience there would be a problem. But we can try to
target things and set expectations.​

​I agree that the "what's in it for me?" question is important.​


> I agree that the value proposition is poorly defined and must be improved,
> but claiming that it is absent is simply not true.
>

​It's absent from this discussion :)​  And I haven't seen it articulated
clearly, such that everyone broadly agrees with it. We should try to create
that.


> That's of course not true either; you can achieve growth in many ways, but
> easiest is to grow in the known product / known market combination. That
> was what I hinted at; if you want to do cross-selling (known product in new
> market), you obviously have to express your benefits in terms of their
> concerns; using your track-record in your known market to show credibility.
> And this is of course much harder! I'm not against it, I just want to warn
> you that our success rate is therefore likely
> smaller, and given the limited resources we have I am not sure we should
> go that way. I believe or "home market" has more than sufficient
> opportunities for growth.
>

​So this just comes back to target markets again. I'm thinking about
ICL/Fujitsu, as I said. If you start telling them about safety critical
usage, they will switch off.​ I agree it's easier to stick with the known
markets, but that's not what I have in mind.

Yes, very much so in the case of TLA (for those who ever witnessed a
> specification in that notation). My point is more general: our unique
> selling point *IS* our notation; it is at the heart of everything we do. We
> have to find a clever way to make that point without showing (specs
> considered scary) details. The obvious way to do that is to illustrate its
> impact during design and analysis (the competence of asking questions [and
> proposing solutions] that matter to the stakeholder).
>

​I agree the notation - the idea of Formal Specification - is important.
But for a presentation, we mustn't show them any - or at least be very
choosy of we do.​ I don't think we're disagreeing here.


> I won't reiterate my point of the plurality of the target audience and the
> need for multi-level selling. But I have another point and that is that our
> notation is easier to adopt than most other formal techniques available.
>

​Yes, and I made the same point in a review of a paper recently about ​a
review of the pros and cons of various methodologies. The fact that we have
an ASCII binding is very important, and the fact that we define
functions/ops over state and data types is easy to grasp.


> Why do you assume that saving money is at all important?


​Because it is in ICL/Fujitsu.​ Ultimately, this must be true for a
business.


> Is that the (short-term) objective that Joe-the-average-manager really
> worries about? I would argue that [cutting down] development time is prime;
> that's what keeps him awake at night.
>

​Mmmm, ok, if we come right down into small development teams that may be
true. But unless that manager can post a cost saving "up" to the
departmental management (or unless it was their idea), he won't be allowed
to use the technique again, because of money (=overspend on the budget,
unless it's a T&M contract).


> C has been around for a while now too and it is still being adopted quite
> often...
>

​True. But the adoption curve is about the human reaction to new
technologies as they spread out to people who don't already know about
them. Since C is well known, if there was (somehow!) a push to adopt it for
some reason, everyone along the curve could react at the same time because
they already understand it.​ It's not a big point, but you mentioned the
curve. I'm saying we need to be careful about assuming it applies as usual.


> ​> I claim that would distort the normal adoption process, so we do have
> to be careful here.
>
> Well, then you have to back up your claim. With respect to prejudice,
> again, most of them are myths or partial truths - that usually similarly
> apply to the "solutions" offered or practices preached by those that make
> these same claims. The only way to deal with this is to take those
> prejudices head-on, first of all by being fair on what we can and cannot
> do. If they will not accept this at face value, stop wasting time
> convincing non-believers and move on.
>

​Again, it's not a big point, but I'm worried that the prejudices will
distort the adoption curve. I can't prove it. But I have a rational
argument that this may not go the way adoption usually does.​

​The common prejudices are based in fact, but missing the nuances that mean
they are not show stoppers.​ Explaining nuances can be tricky in the face
of blind prejudice!

We are educating quite a few of them in universities in DK, UK and Japan,
> how can we enable those young enthusiastic professionals to make their case
> in their companies, convince their managers?
>

​Before their enthusiasm is completely drained by the awful reality of it
:-)

I would say this is yet another slightly different "pitch"​. You would not
give the same arguments to the fresh recruit that you would make to the
senior management and engineers (fresh faces are ignored until they can
prove their worth).


> I wish evidence would make a difference; in practice it is hardly ever
> perceived as that. One of the key problems in our field is these kind of
> (management) decisions are not taken rationally as there is no history of
> empirical research.


​Yes. They are often just following fashion/Zeitgeists, so that they can
pad their CVs for when they move on.

The best convincing evidence we can provide IMHO is that we do ourselves as
> we preach. I'd like to hear your opinion about that!
>

​Yes, we must do that - though here (FJ) at least that is difficult.​ So we
still don't have a clearly defined value proposition... :-(  To me it's
something like this:

The problem:

   - You want to deliver software solutions quickly because time to market
   matters
   - You have found that waterfall style designs take up a lot of time, and
   you don't deliver those documents so it is not apparently helping. This is
   commonly known.
   - You think that Agile techniques help, because they are quick and your
   engineers like it. It is also "current best practice".
   - And you are delivering quickly, so that must be OK.
   - But you are also delivering a hidden dependency: your customers are
   dependent on you to keep the development team together. This is because
   although they "backlog" the design specs, they are never enough to maintain
   or extend the system unless the original developers do it.
   - You cannot maintain your development team in general - the best
   usually leave quickly after Phase 1, because no one wants to do maintenance.
   - So Phases 2, 3 and so on cost a lot more, have endless problems, and
   end up costing a lot more. Entire subsystems are "dark code" because they
   are critically important and completely unknown. You dare not change them.
   - The customer wants to know why you are suddenly more expensive, and
   feels duped.

​The solution:

   - If you spend time building an abstract formal model, you can ​show it
   to your customers (via animation) early in the development, just as you
   would (on a white board) with Agile.
   - This model can be tested, before development starts - by you or the
   customer or both. This de-risks the project.
   - You need to take steps to ensure the coding then follows the model,
   allowing for the abstraction. This requires discipline. Code generation may
   help.
   - Continuous integration can run model tests and code/unit tests
   together, to check that the code continues to follow the specification as
   development proceeds. You can't check-in code that does not follow the
   model.
   - Your test team can use the model as an "Oracle" to check the delivered
   behaviour against the specification. You may even be able to use it in
   negotiation with the customer, when they dispute the functional requirement.
   - After the team splits up, the model stays with the system and must be
   maintained with it. It is far more reliable than paper documentation, and
   enables you to perform maintenance and upgrades with less risk.
   - When Phase 2 comes along, the model is updated first, then the code
   modified to match. There should be no "dark code" because everything is
   described by the model.
   - So overall the customer gets consistent delivery and high quality, and
   is happy :-)

​Something like that anyway. Did I miss anything? :-)

-- 
Cheers,
-nick

**Comment by tomooda** [comment]
Here I dump my thoughts on this topic.

* I basically agree with the "solution" section of Nick's last post.
* I'd add "VDM can be applied partially. You can choose a narrow scope within your project where quality really matters" between the first and the second item.
* Being testable is a good value of VDM, but we have to stop the audience from saying "Yes, we are already doing that in Java, thank you". We should say it *reinforces* their way of testing and reviewing artifacts.

**Comment by ldcouto** [comment]
As an industrial person now, I have been thinking of ways to pitch VDM to colleagues. 

The thing with VDM, as I see it, is that it's somewhere between rapid prototyping with programming languages and "hardcore" formal methods.

The notation is easier on the eyes than something like TLA+ but the analyses are less powerful (at least, the analyses that we currently have available in our tools). On the other hand, it's more rigorous than something like Ruby or Scala but it will take longer to prototype stuff.

As always, this can either be seen as a negative or as a positive. It's all about the tradeoffs. We just need to come up with a good way to tell the story.  For example,  it's already been mentioned but one of the big strengths of VDM is the syntax -- it's very close to C-style so it's easy for programmers and certain kinds engineers to pick up. This is a huge benefit -- we can easily show some nasty FM notation as a comparison.

So, one way forward for this video might be to identify the tradeoffs between VDM and Hardcore FM and VDM and PL. And then come up with a nice narrative that explains why the tradeoffs come out in favor of VDM :)

**Comment by nickbattle** [comment]
Welcome to the wonderful world of industry Luis :)  I'm sure you've already discovered some of the differences from academia!

I think I'd agree that we're trying to highlight the tradeoffs and benefits. That's what I was calling the value proposition in the discussion so far. Accessibility of the notation does come into it, though perhaps after more difficult descisions have been taken about what methods to adopt. I'm not saying notation isn't important, but that is a barrier of "familiarity" rather than anything more substantial.

Have you had any discussions with, or hints about how your new employer feels about formality? Do you have any formal specification in your existing processes?

**Comment by ldcouto** [comment]
The company is very big so it varies a lot. Some groups use FM a lot and some not at all. The ones who use FM are using more hardcore stuff like model checking. I don't think we'll have much chance convincing those kinds of users to migrate until we can deliver the same level of result -- counter-examples are really nice!

But I think the groups that don't use any FM in their processes might be more amenable to trying out VDM, if we can show tangible value. Stuff like "gain insight and reduce errors" seems too vague, even if it is true.

Does anyone have any experience with getting C-style programmers to try out VDM?

**Comment by kgpierce** [comment]
Issue closed until such time as we want to look at a video again.
