### ISSUE TITLE
Licensing of Fujitsu's VDMJ

### ISSUE THREAD

**Issue by nickbattle** [overturetool/overturetool.github.io#32]
New action for PGL to contact MV (cc NB) about the approach to updating the licensing of Fujitsu’s VDMJ, to allow it to be integrated with the Eclipse platform in Overture and other derived tool projects.

**Comment by nlmave** [comment]
Yes, the action to review the licence of Overture is indeed still not completed - my bad. But the licensing for VDMJ is a separate issue altogether. As identified, including VDMJ into Eclipse is difficult due to license GPL restrictions. Either Fujitsu allows it to be used in Eclipse by adding the additional clause to the GPL, or they should reconsider changing the license model altogether - i.e. to move to BSD two-clause. What kind of info do you need to continue further?

**Comment by nickbattle** [comment]
Fujitsu won't immediately understand the issue or options, so we need to be able to clearly explain what we want them to do (and ideally, why that won't cost them anything, including effort to make the change).

VDMJ is GPL3. Overture's "command line" is a derived work, and therefore needs to be GPL compatible, I think, as things stand? To be integrated with Eclipse, Overture needs to be compatible with Eclipse's license, but GPL isn't.

So what is this additional GPL clause? Is it the same as https://en.wikipedia.org/wiki/GPL_linking_exception?

We're sure BSD two-clause is compatible with Eclipse?

Which of these options is easiest for us?

Is this enough to gain compliance for other derived works (derived from Overture - I'm not sure of the status of DESTECS, Crescendo, Symphony and INTO-CPS)? If we have to ask for another license change for Digital Twins, that will be unfortunate.

**Comment by nlmave** [comment]
For Java applications, the GNU classpath exception is more generally applicable, see https://en.wikipedia.org/wiki/GNU_Classpath and https://www.eclipse.org/org/documents/GPL_CE_Policy.php, but this is indeed a GPL with linking exception variant (for Java).

The article https://www.fsf.org/blogs/licensing/using-the-gpl-for-eclipse-plug-ins provides a good overview too, and refers to http://www.gnu.org/licenses/gpl-faq.html#GPLIncompatibleLibs for how to change the license (the infamous GPL v3 section 7). The down side to this approach is that you have to maintain this (section 7) definition. A generic statement like "Overture and all derived tools" is probably not acceptable as a proper legal definition. So it may imply that you have to update the license each time a new tool is written that  uses VDMJ in library form (i.e. VDMPad etc), which would require Fujitsu legal to do some pro-bono work for the Overture community.

BSD two-clause is the most liberal OSS license available. It allows and permits derived works without any limitation and without the need to open source the derivation. Basically, it only protects the copyright  and limits the liability of the original author. This license is used a lot for OSS that is sold commercially (i.e prepackaged in some tool, or part of some on-line pay-per-use service). To answer your last question (ease of use), just look at BSD two-clause, even I can understand how it works, need I say more?  https://opensource.org/licenses/BSD-2-Clause

For the rest of Overture, the approach can be more straightforward. If all committers (those registered to github that actually made commits to the repository) agree to change the licence (e.g. to BSD two-clause) then we can release a new version of Overture under that new license regime. That does not revoke the license conditions of the existing version of Overture, but that version will then simply not be maintained any more (at least not by us) so eventually will die out (as a matter of fact this would also apply to VDMJ).

The potential change of the license of Overture does not change the problem of VDMJ by the way, because the GPLv3 is the root cause of the issue.

As an aside, note that also the Java license conditions have changed with Java 9 - we may need to switch to OpenJDK permanently in order to remain useable without a requiring our end-users to buy a commercial license from Oracle for the JVM.

As a second aside, there are products on the market that have a dual license scheme; OSS for non-commercial use and a closed source license for commercial use; GNAT and Modelica being two off them. As far as I can see, this would not work for VDMJ as the basic problem remains: GPLv3 is not compatible with the Eclipse Public License.

On compatibility of BSD with EPL, I think so, but just have a look at https://www.eclipse.org/legal/epl-2.0/faq.php and you'll see it ain't easy to answer that question.

I am *not* a licensing expert - professional advice should be sought to define the path forward, especially if the use in new ventures is considered.

**Comment by nickbattle** [comment]
OK... complicated, but thanks for explaining all that background. I probably shouldn't try to predict Fujitsu's likely reaction to a request to change licensing, but VDMJ is not anything "mainstream" to them - they most likely don't understand what it is for and will only vaguely be aware that they have this IPR (because I told them, before I left). With luck, and if we offer to do all of the admin changes needed, they might accept a BSD two-clause. But... I'd like to have all our ducks in a row before we ask.

Peter, do you know whether Aarhus (or Newcastle, come to that) might have experts in this area who could advise/help?

**Comment by nlmave** [comment]
I understand there is now a legal entity set up to support INTO-CPS maintenance? Perhaps FJ might be interested to transfer IPR to that entity (as an in kind contribution) allowing them to change the license?

**Comment by nlmave** [comment]
Anyway, the short story is:
- GPLv3 does not allow integration of VDMJ into other tools, as it enforces the open source nature also on derived works
- by adding Section 7, an exception can be made for some tools (such as Overture); however if new tools arrive, this list (in the license) needs to be updated, requiring regular updates of the license
- alternatively, VDMJ could be relicensed under BSD two-clause, which keeps IPR at and limits liability for FJ, but gives downstream users complete freedom to use (also commercially) and modify (without need to open source these changes).
- thirdly, they could consider moving the IPR to another party (a physical person or some other legal entity)

.. my two cents worth .. hope this helps!

**Comment by nickbattle** [comment]
Thanks Marcel, that does summarise it very clearly.

I know that Fujitsu have a (stated) policy of never selling IPR, unless it is part of some other larger deal. We can ask, but I think they are unlikely to give it to INTO-CPS (and even less likely to do so for free).

If we repeatedly ask them to make changes to a GPL section 7 amendment, you can see that is going to be work for them with no particular advantage. They might do it once, but beyond that we would be depending on their generosity.

If we ask them to move to BSD two-clause, we would need to provide a good justification of why that helps them. It seems to reduce their control over the product, though perhaps the argument would be that by *not* doing so, the product will never be used extensively and hence there are limited future opportunities.

Another avenue occurs to me... VDM is popular in Japan, as you know, and Fujitsu UK has a Japanese parent company. We may be able to persuade FJ UK to transfer the IPR internally to FJ Japan, if we can find people there who are interested - I used to have contacts who used Overture, and we have Overture/VDM people on the ground in Japan anyway. If the IPR was transferred to a VDM-friendly country (but still within FJ) they might be more inclined to re-license it going forward.

**Comment by nickbattle** [comment]
I've just discovered that the people I used to know who dealt with IPR within the Fujitsu legal team have moved on. Bizarrely, when I asked friends who are still in the company to find out who the new head of IPR is, they were told that we (ie. Overture) would have to ask Fujitsu who it is - they wouldn't tell my friend (huh??). That sounds like organisational confusion to me. My guess is that no one is really looking after IPR officially and they deal with things on a case by case basis. That may be fine, but it won't be quite as easy as I'd hoped.

**Comment by nickbattle** [comment]
After exploring the options here, it seems the best way forward is to give in to GPL licensing restrictions and bundle everything to do with VDMJ under that license. As we are planning to move from Overture/Eclipse to VSCode anyway, and since this platform does not place license restrictions on its plugins ("extensions") this means that we will become license compliant as long as all work associated with the tooling uses the GPL license. So the new VDM VSCode extenstion has to be GPL.

This issue can therefore be closed, as decided at the Overture net meeting on 2nd May 2021.
